"""Make question answers nullable and add answer_set_at timestamp

Revision ID: 3267ebb24c36
Revises: 4a26a083a036
Create Date: 2025-07-03 22:24:48.062402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3267ebb24c36'
down_revision = '4a26a083a036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_set_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('correct_answer',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('answer_set_at')

    # ### end Alembic commands ###
