"""Add contest_invitations table

Revision ID: 3fd936ea50af
Revises: 84c6795ef3f9
Create Date: 2025-07-04 12:58:30.409543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd936ea50af'
down_revision = '84c6795ef3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_invitations',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('invitation_type', sa.String(length=10), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.contest_id'], ),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contest_invitations')
    # ### end Alembic commands ###
