"""Add Google OAuth fields to User model

Revision ID: add_google_oauth_fields
Revises: 99b5f12b5c77
Create Date: 2025-01-05 09:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_google_oauth_fields'
down_revision = '99b5f12b5c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('google_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('google_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('google_picture', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=False, server_default='email'))
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('google_picture')
        batch_op.drop_column('google_name')
        batch_op.drop_column('google_email')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
