"""Add is_ai_generated field to Contest model

Revision ID: c43685dc2f29
Revises: add_google_oauth_fields
Create Date: 2025-07-11 14:54:59.973853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43685dc2f29'
down_revision = 'add_google_oauth_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.drop_column('is_ai_generated')

    # ### end Alembic commands ###
